package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SettingsSync'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("SettingsSync")
    name = "settings-sync"
    url = "https://github.com/Valrravn/teamcity-versioned-settings"
    branch = "main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "Valrravn"
        password = "credentialsJSON:44a02572-22ac-4888-a5a9-4186fb062ddb"
    }
}))

